version: '3'
services:
  backend: 
  
    image: rnolas96/dev-engagement-backend:dev  
    container_name: api-container-engagement-dev
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8005:8000'
  
  frontend:
    image: rnolas96/dev-engagement-frontend:dev
    container_name: gui-container-engagement-dev
    ports:
      - '3005:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  dev-redis_data: