version: '3'
services:
  backend: 
  
    image: vshar17/engagement-metric-backend-img:prod
    container_name: api-container-engagement
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8005:8000'
  
  frontend:
    image: vshar17/engagement-metric-frontend-img:prod
    container_name: gui-container-engagement
    ports:
      - '3005:80'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  dev-redis_data:
