version: '3'
services:
  backend: 
  
    image: engagementmetric-backend
    container_name: api-container-engagement
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8005:8000'
  
  frontend:
    image: engagementmetric-frontend
    container_name: gui-container-engagement
    ports:
      - '3005:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  dev-redis_data: