version: '3'
services:
  backend: 
  
    image: avijay48/sbpbcoupling-backend-img:prod  
    container_name: sbpbcoupling-api-container
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8082:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-sbpbcoupling
    ports:
      - '6382:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
    image: avijay48/sbpbcoupling-frontend-img:prod
    container_name: gui-container-sbpbcoupling
    ports:
      - '3002:80'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  prod-redis_data: