version: '3'
services:
  backend: 
  
    image: vshar17/burndownmetric-backend-img:prod  
    container_name: api-container-burndown
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8080:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-burndown
    ports:
      - '6380:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
<<<<<<< Updated upstream
    image: rnolas96/prod-burndownmetric-frontend:prod
=======
    image: vshar17/burndownmetric-frontend-img:prod
>>>>>>> Stashed changes
    container_name: gui-container-burndown
    ports:
      - '3030:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  prod-redis_data: