version: '3'
services:
  backend: 
  
    image: rnolas96/leadtime-backend-img:prod
    container_name: leadime-api-container
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8086:8000'
  
  
  frontend:
    image: rnolas96/leadtime-frontend-img:prod
    container_name: leadtime-gui-container
    ports:
      - '3036:80'
    links:
      - backend 
    stdin_open: true
    tty: true
