version: '3'
services:
  backend: 
  
    image: avijay48/taskcoupling-backend-img:prod  
    container_name: taskcoupling-api-container
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8084:8000'
 
  
  frontend:
    image: avijay48/taskcoupling-frontend-img:prod
    container_name: taskcoupling-gui-container
    ports:
      - '3004:80'
    links:
      - backend 
    stdin_open: true
    tty: true
