version: '3'
services:
  backend: 
  
    image: rnolas96/prod-costofdelaymetric-backend:prod  
    container_name: api-container-costofdelay-prod
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8081:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-costofdelay-prod
    ports:
      - '6381:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
    image: rnolas96/prod-costofdelaymetric-frontend:prod
    container_name: gui-container-costofdelay-prod
    ports:
      - '3031:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  prod-redis_data: