version: '3'
services:
  backend: 
  
    image: vshar17/costofdelay-metric-backend-img:prod
    container_name: api-container-costofdelay
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8081:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-costofdelay
    ports:
      - '6369:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
    image: vshar17/costofdelay-metric-frontend-img:prod
    container_name: gui-container-costofdelay
    ports:
      - '3006:80'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  prod-redis_data:
