version: '3'
services:
  backend: 
  
    image: avijay48/taigabackend:dev  
    container_name: api-container-dev
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8000:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-dev
    ports:
      - '6379:6379'
    volumes:
      - dev-redis_data:/data
  
  frontend:
    image: avijay48/taigafrontend:dev
    container_name: gui-container-dev
    ports:
      - '3000:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  dev-redis_data: