version: '3'
services:
  backend: 
    build: ./backend
    container_name: api-container
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8000:8000'

  
  frontend:
    build: ./frontend
    container_name: gui-container
    ports:
      - '3000:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
