version: '3'
services:
  backend: 
    image: avijay48/periodtwo-taigaproject-backend:periodtwo
    container_name: api-container-periodtwo
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8090:8000'

  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-prod
    ports:
      - '6390:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
    image: avijay48/periodtwo-taigaproject-frontend:periodtwo
    container_name: gui-container-periodtwo
    ports:
      - '3040:3000'
    links:
      - backend 
    stdin_open: true
    tty: true

volumes:
  prod-redis_data: