version: '3'
services:
  backend: 
    build: ./backend/reactApi
    container_name: api-container
                                    
    ports:
      - '8000:8000'

  
  frontend:
    build: ./frontend
    container_name: gui-container
    ports:
      - '3000:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
