version: '3'
services:
  backend: 
  

    image: avijay48/prod-taigaproject-backend:prod  
    container_name: api-container-prod
    environment:
      - TAIGA_URL=https://api.taiga.io/api/v1
    ports:
      - '8080:8000'
  
  redis:
    image: redis   # Using the official Redis image from Docker Hub
    container_name: redis-container-prod
    ports:
      - '6380:6379'
    volumes:
      - prod-redis_data:/data
  
  frontend:
    image: avijay48/prod-taigaproject-frontend:prod
    container_name: gui-container-prod
    ports:
      - '3030:3000'
    links:
      - backend 
    stdin_open: true
    tty: true
volumes: 
  prod-redis_data: